/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.anomaly.inventrack.ui.panels;

import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;

/**
 *
 * @author user
 */
public class BrandingPanel extends javax.swing.JPanel {

    /**
     * Creates new form BrandingPanel
     */
    
    public static final Color COLOR_TEAL = new Color(170, 204, 213);
    public static final Color COLOR_WHITE = Color.WHITE;
    public static final Color COLOR_BLACK = Color.BLACK;
    public static final Color COLOR_LIGHT_GRAY = new Color(220, 220, 220);
    
    public BrandingPanel() {
        initComponents();
        initCustomStyle();
    }
    
    private void initCustomStyle() {
        setBackground(COLOR_TEAL); 
        
        try {
            java.net.URL logoURL = getClass().getResource("/img/logo_inventrack.png");
            if (logoURL != null) {
                ImageIcon logoIcon = new ImageIcon(logoURL);
                lblLogo.setIcon(logoIcon);
                lblLogo.setText("");
            } else {
                lblLogo.setText("LOGO");
                lblLogo.setFont(new Font("Arial", Font.BOLD, 48));
                lblLogo.setForeground(COLOR_WHITE);
            }
        } catch (Exception e) {
            lblLogo.setText("LOGO (Error)");
            lblLogo.setForeground(COLOR_WHITE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCopyright = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(170, 204, 213));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(new javax.swing.OverlayLayout(this));

        lblCopyright.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCopyright.setForeground(new java.awt.Color(255, 255, 255));
        lblCopyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCopyright.setText("copyright © anomaly all rights reserved");
        lblCopyright.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblCopyright.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lblCopyright.setMaximumSize(new java.awt.Dimension(500, 450));
        lblCopyright.setMinimumSize(new java.awt.Dimension(500, 450));
        lblCopyright.setPreferredSize(new java.awt.Dimension(500, 450));
        lblCopyright.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(lblCopyright);

        lblLogo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_inventrack.png"))); // NOI18N
        lblLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblLogo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(lblLogo);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCopyright;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
