/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.anomaly.inventrack.ui.panels;

import com.anomaly.inventrack.models.Pengguna;

/**
 *
 * @author user
 */
public class DashboardFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardFrame.class.getName());
    private Pengguna currentUser;

    /**
     * Creates new form DashboardFrame
     */
    public DashboardFrame() {
        initComponents();
    }

    public DashboardFrame(Pengguna pengguna) {
        initComponents(); // 1. PENTING: Inisialisasi komponen GUI (tombol, label, dll)
        
        this.currentUser = pengguna; // 2. Simpan data pengguna ke variabel global
        
        if (this.currentUser != null) {
            String nama = this.currentUser.getNamaPengguna();

            // Panggil method 'Pintu Masuk' yang kita buat di Langkah 1 tadi
            // sidebarPanel1 adalah nama variabel komponen yang Anda drag-drop tadi
            sidebarPanel.setNamaUser(nama);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel = new com.anomaly.inventrack.ui.panels.SidebarPanel();
        dashboardPanel = new com.anomaly.inventrack.ui.panels.DashboardPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(803, 500));
        getContentPane().add(sidebarPanel, java.awt.BorderLayout.WEST);
        getContentPane().add(dashboardPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.anomaly.inventrack.ui.panels.DashboardPanel dashboardPanel;
    private com.anomaly.inventrack.ui.panels.SidebarPanel sidebarPanel;
    // End of variables declaration//GEN-END:variables
}
