/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.anomaly.inventrack.ui.panels;

import com.anomaly.inventrack.models.Pengguna;
import java.awt.CardLayout;
import java.awt.Component;



/**
 *
 * @author user
 */
public class DashboardPanel extends javax.swing.JPanel {
    
    private StokBarangPanel pStok;
    private DaftarPermintaanPanel pDaftarPermintaan;
    private TambahBarangPanel pTambahBarang;
    private EditStokPanel pEditStok;

    /**
     * Creates new form DashboardPanel
     */
    public DashboardPanel() {
        initComponents();
        
        //Nanti dihapus
        if (java.beans.Beans.isDesignTime()) {
            return;
        }
        
        setLayout(new CardLayout());
        

        // Inisialisasi panel-panel
        pStok = new StokBarangPanel();
        pDaftarPermintaan = new DaftarPermintaanPanel();
        pTambahBarang = new TambahBarangPanel();
        pEditStok = new EditStokPanel();

        // Tambahkan ke CardLayout
        add(pStok, "cardStok");
        add(pDaftarPermintaan, "cardDaftarPermintaan");
        add(pTambahBarang, "cardTambahBarang");
        add(pEditStok, "cardEditStok");
    }
    
    public void setLoggedInUser(Pengguna user) {
        // Kirim ke EditStokPanel (pEditStok adalah nama variabel panel edit stok Anda)
        if (pEditStok != null) {
            pEditStok.setCurrentUser(user);
        }
        
        // Jika ada panel lain yang butuh user, kirim juga di sini
        // if (pTambahBarang != null) pTambahBarang.setUser(user);
    }
    
    public void refreshDataTambahBarang() {
        pTambahBarang.loadHelperData();
    }
    
    public void showForm(String cardName) {
        CardLayout cl = (CardLayout) getLayout();
        cl.show(this, cardName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
