/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.anomaly.inventrack.ui.panels;

import com.anomaly.inventrack.models.Pengguna;
import java.awt.CardLayout;
import java.awt.Component;



/**
 *
 * @author user
 */
public class DashboardPanel extends javax.swing.JPanel {
    
    private StokBarangPanel pStok;
    private DaftarPermintaanPanel pDaftarPermintaan;
    private TambahBarangPanel pTambahBarang;
    private EditStokPanel pEditStok;
    private BuatPermintaanPanel pBuatPermintaan;
    private DaftarPengirimanPanel pDaftarPengiriman;
    private LogStokPanel pLogStok;
    private BuatPengirimanPanel pBuatPengiriman;

    /**
     * Creates new form DashboardPanel
     */
    public DashboardPanel() {
        initComponents();
        
        setLayout(new CardLayout());
        
        pStok = new StokBarangPanel();
        pDaftarPermintaan = new DaftarPermintaanPanel();
        pTambahBarang = new TambahBarangPanel();
        pEditStok = new EditStokPanel();
        pBuatPermintaan = new BuatPermintaanPanel();
        pDaftarPengiriman = new DaftarPengirimanPanel();
        pLogStok = new LogStokPanel();
        pBuatPengiriman = new BuatPengirimanPanel();

        add(pStok, "cardStok");
        add(pDaftarPermintaan, "cardDaftarPermintaan");
        add(pTambahBarang, "cardTambahBarang");
        add(pEditStok, "cardEditStok");
        add(pBuatPermintaan, "cardBuatPermintaan");
        add(pDaftarPengiriman, "cardDaftarPengiriman");
        add(pLogStok, "cardLogStok");
        add(pBuatPengiriman, "cardBuatPengiriman");
    }
    
    public void setLoggedInUser(Pengguna user) {
        if (pEditStok != null) {
            pEditStok.setCurrentUser(user);
        }
 
        if (pDaftarPermintaan != null) {
            pDaftarPermintaan.setCurrentUser(user);
        }
        
        if (pBuatPermintaan != null) {
            pBuatPermintaan.setCurrentUser(user);
        } 
        
        if (pDaftarPengiriman != null) {
            pDaftarPengiriman.setCurrentUser(user);
        }
        
        if (pLogStok != null) {
            pLogStok.setCurrentUser(user);
        }
        
        if (pBuatPengiriman != null) {
            pBuatPengiriman.setCurrentUser(user);
        }
    }
    
    public void refreshDataTambahBarang() {
        pTambahBarang.loadHelperData();
    }
    
    public void showForm(String cardName) {
        CardLayout cl = (CardLayout) getLayout();
        cl.show(this, cardName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
