/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.anomaly.inventrack.ui.panels;

import java.awt.CardLayout;
import java.awt.Component;



/**
 *
 * @author user
 */
public class DashboardPanel extends javax.swing.JPanel {
    
    private StokBarangPanel pStok;
    private DaftarPermintaanPanel pDaftarPermintaan;
    private TambahBarangPanel pTambahBarang;

    /**
     * Creates new form DashboardPanel
     */
    public DashboardPanel() {
        initComponents();
        setLayout(new CardLayout());

        // Inisialisasi panel-panel
        pStok = new StokBarangPanel();
        pDaftarPermintaan = new DaftarPermintaanPanel();
        pTambahBarang = new TambahBarangPanel();

        // Tambahkan ke CardLayout
        add(pStok, "cardStok");
        add(pDaftarPermintaan, "cardDaftarPermintaan");
        add(pTambahBarang, "cardTambahBarang");
        
        // ...
    }
    
    public void refreshDataTambahBarang() {
        pTambahBarang.loadHelperData();
    }
    
    public void showForm(String cardName) {
        CardLayout cl = (CardLayout) getLayout();
        cl.show(this, cardName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
