/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.anomaly.inventrack.ui.panels;

import com.anomaly.inventrack.controllers.InventrackController;
import com.anomaly.inventrack.models.Pengguna;
import com.anomaly.inventrack.ui.InvenTrackApp;
import com.anomaly.inventrack.ui.panels.BrandingPanel;

import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.util.Optional;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class LoginPanel extends javax.swing.JPanel {

    private InvenTrackApp mainApp;
    private InventrackController controller;

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
    }
    
    public LoginPanel(InvenTrackApp mainApp) {
        this(); // Panggil constructor default untuk init komponen visual
        this.mainApp = mainApp;
        this.controller = mainApp.getController();
        
        initCustomListeners();
    }

    private void initCustomListeners() {
        // Listener tombol Login
        btnLogin.addActionListener(this::handleLogin);
        
        // Listener Enter di password
        txtPassword.addActionListener(this::handleLogin);
        
    }

    private void handleLogin(ActionEvent e) {
        String username = txtUsername.getText();
        String password = new String(txtPassword.getPassword());

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Username dan Password wajib diisi!", 
                "Peringatan", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Ubah kursor jadi loading
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        
        // Proses login via controller
        Optional<Pengguna> loginResult = Optional.empty();
        if (controller != null) {
            loginResult = controller.login(username, password);
        } else {
            System.err.println("Controller belum diinisialisasi!");
        }
        
        setCursor(Cursor.getDefaultCursor());

        if (loginResult.isPresent()) {
            if (mainApp != null) {
                mainApp.showDashboard(loginResult.get());
            }
        } else {
            JOptionPane.showMessageDialog(this, 
                "Login Gagal. Cek kembali username atau password Anda.", 
                "Gagal Masuk", 
                JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jOptionPane2 = new javax.swing.JOptionPane();
        brandingPanel1 = new com.anomaly.inventrack.ui.panels.BrandingPanel();
        jPanel1 = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1000, 500));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setPreferredSize(new java.awt.Dimension(1000, 500));
        setLayout(new java.awt.GridLayout());
        add(brandingPanel1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblLogin.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        lblLogin.setText("LOGIN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 8, 40, 8);
        jPanel1.add(lblLogin, gridBagConstraints);

        lblUsername.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUsername.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(15, 35, 15, 15);
        jPanel1.add(lblUsername, gridBagConstraints);

        lblPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPassword.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(15, 35, 15, 15);
        jPanel1.add(lblPassword, gridBagConstraints);

        txtUsername.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUsername.setToolTipText("");
        txtUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUsername.setMinimumSize(new java.awt.Dimension(64, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 35);
        jPanel1.add(txtUsername, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 35);
        jPanel1.add(txtPassword, gridBagConstraints);

        btnLogin.setText("Login");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 25, 0);
        jPanel1.add(btnLogin, gridBagConstraints);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.anomaly.inventrack.ui.panels.BrandingPanel brandingPanel1;
    private javax.swing.JButton btnLogin;
    private javax.swing.JOptionPane jOptionPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
