/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.anomaly.inventrack.ui.panels;

import com.anomaly.inventrack.models.Pengguna;
import com.anomaly.inventrack.models.Gudang;
import com.anomaly.inventrack.repositories.GudangRepositories;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.JPanel;
import java.util.Optional;

/**
 *
 * @author user
 */
public class SidebarPanel extends javax.swing.JPanel {
    
    private static final int ID_GUDANG_UTAMA = 11011;
    
    private DashboardPanel panelUtama;
      
    /**
     * Creates new form MenuPanel
     */
    public SidebarPanel() {
        initComponents();
        hideAllSubmenus();
    }
    
    public void setNamaUser(Pengguna pengguna) {
        if (pengguna != null) {
            lblUsername.setText(pengguna.getNamaPengguna());
            
            GudangRepositories gudangRepo = new GudangRepositories();
            Optional<Gudang> optGudang = gudangRepo.findById(pengguna.getIdGudang());
            
            if (optGudang.isPresent()) {
                lblNamaGudang.setText(optGudang.get().getNamaGudang());
            } else {
                lblNamaGudang.setText("Gudang Tidak Dikenal");
            }
            
            boolean isAdminPusat = (pengguna.getIdGudang() == ID_GUDANG_UTAMA);

            btnTambahBarang.setVisible(isAdminPusat);

            pnlSubMenuBarang.revalidate();
            pnlSubMenuBarang.repaint();
        }
    }
    
    
    private void hideAllSubmenus() {
        if (pnlSubMenuBarang != null) pnlSubMenuBarang.setVisible(false);
        if (pnlSubMenuPermintaan != null) pnlSubMenuPermintaan.setVisible(false);
 
        this.revalidate();
        this.repaint();
    }
    
    private void toggleSubmenu(JPanel subPanel) {
        boolean isVisible = subPanel.isVisible();

        // 1. Ubah status visibilitas
        subPanel.setVisible(!isVisible);

        this.revalidate(); 
        this.repaint();
    }
    
    public void setPanelUtama(DashboardPanel dp) {
        this.panelUtama = dp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlProfile = new javax.swing.JPanel();
        icnInventrack = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblNamaGudang = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlMenuContainer = new javax.swing.JPanel();
        btnMenuBarang = new javax.swing.JButton();
        pnlSubMenuBarang = new javax.swing.JPanel();
        btnSubMenuStok = new javax.swing.JButton();
        btnTambahBarang = new javax.swing.JButton();
        btnSubMenuEditStok = new javax.swing.JButton();
        btnMenuPermintaan = new javax.swing.JButton();
        pnlSubMenuPermintaan = new javax.swing.JPanel();
        btnSubMenuPermintaan = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        pnlProfile.setBackground(new java.awt.Color(170, 204, 213));
        pnlProfile.setLayout(new java.awt.GridBagLayout());

        icnInventrack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_inventrack.png"))); // NOI18N
        icnInventrack.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        pnlProfile.add(icnInventrack, new java.awt.GridBagConstraints());

        lblUsername.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        pnlProfile.add(lblUsername, gridBagConstraints);

        lblNamaGudang.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        pnlProfile.add(lblNamaGudang, gridBagConstraints);

        add(pnlProfile, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBackground(new java.awt.Color(170, 204, 213));
        jScrollPane1.setBorder(null);

        pnlMenuContainer.setBackground(new java.awt.Color(170, 204, 213));
        pnlMenuContainer.setLayout(new java.awt.GridBagLayout());

        btnMenuBarang.setBackground(new java.awt.Color(170, 204, 213));
        btnMenuBarang.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMenuBarang.setText("Barang");
        btnMenuBarang.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnMenuBarang.setContentAreaFilled(false);
        btnMenuBarang.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnMenuBarang.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnMenuBarang.addActionListener(this::btnMenuBarangActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlMenuContainer.add(btnMenuBarang, gridBagConstraints);

        pnlSubMenuBarang.setBackground(new java.awt.Color(170, 204, 213));
        pnlSubMenuBarang.setLayout(new java.awt.GridBagLayout());

        btnSubMenuStok.setBackground(new java.awt.Color(170, 204, 213));
        btnSubMenuStok.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSubMenuStok.setText("Stok");
        btnSubMenuStok.setBorder(null);
        btnSubMenuStok.setBorderPainted(false);
        btnSubMenuStok.setContentAreaFilled(false);
        btnSubMenuStok.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnSubMenuStok.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnSubMenuStok.addActionListener(this::btnSubMenuStokActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlSubMenuBarang.add(btnSubMenuStok, gridBagConstraints);

        btnTambahBarang.setBackground(new java.awt.Color(170, 204, 213));
        btnTambahBarang.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnTambahBarang.setText("Tambah Barang");
        btnTambahBarang.setBorder(null);
        btnTambahBarang.setBorderPainted(false);
        btnTambahBarang.setContentAreaFilled(false);
        btnTambahBarang.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnTambahBarang.addActionListener(this::btnTambahBarangActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlSubMenuBarang.add(btnTambahBarang, gridBagConstraints);

        btnSubMenuEditStok.setBackground(new java.awt.Color(170, 204, 213));
        btnSubMenuEditStok.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSubMenuEditStok.setText("Edit Stok");
        btnSubMenuEditStok.setBorder(null);
        btnSubMenuEditStok.setBorderPainted(false);
        btnSubMenuEditStok.setContentAreaFilled(false);
        btnSubMenuEditStok.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnSubMenuEditStok.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnSubMenuEditStok.addActionListener(this::btnSubMenuEditStokActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlSubMenuBarang.add(btnSubMenuEditStok, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        pnlMenuContainer.add(pnlSubMenuBarang, gridBagConstraints);

        btnMenuPermintaan.setBackground(new java.awt.Color(170, 204, 213));
        btnMenuPermintaan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMenuPermintaan.setText("Permintaan");
        btnMenuPermintaan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnMenuPermintaan.setContentAreaFilled(false);
        btnMenuPermintaan.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnMenuPermintaan.addActionListener(this::btnMenuPermintaanActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlMenuContainer.add(btnMenuPermintaan, gridBagConstraints);

        pnlSubMenuPermintaan.setBackground(new java.awt.Color(170, 204, 213));
        pnlSubMenuPermintaan.setLayout(new java.awt.GridBagLayout());

        btnSubMenuPermintaan.setBackground(new java.awt.Color(170, 204, 213));
        btnSubMenuPermintaan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSubMenuPermintaan.setText("Daftar Permintaan");
        btnSubMenuPermintaan.setBorder(null);
        btnSubMenuPermintaan.setBorderPainted(false);
        btnSubMenuPermintaan.setContentAreaFilled(false);
        btnSubMenuPermintaan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnSubMenuPermintaan.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnSubMenuPermintaan.addActionListener(this::btnSubMenuPermintaanActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlSubMenuPermintaan.add(btnSubMenuPermintaan, gridBagConstraints);

        jButton4.setBackground(new java.awt.Color(170, 204, 213));
        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setText("SubMenu2");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlSubMenuPermintaan.add(jButton4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        pnlMenuContainer.add(pnlSubMenuPermintaan, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(170, 204, 213));
        jPanel1.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 99;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        pnlMenuContainer.add(jPanel1, gridBagConstraints);

        jScrollPane1.setViewportView(pnlMenuContainer);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuBarangActionPerformed
        toggleSubmenu(pnlSubMenuBarang);
    }//GEN-LAST:event_btnMenuBarangActionPerformed

    private void btnMenuPermintaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPermintaanActionPerformed
        toggleSubmenu(pnlSubMenuPermintaan);
    }//GEN-LAST:event_btnMenuPermintaanActionPerformed

    private void btnSubMenuStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubMenuStokActionPerformed
        if (panelUtama != null) {
            panelUtama.showForm("cardStok");
        }
    }//GEN-LAST:event_btnSubMenuStokActionPerformed

    private void btnSubMenuPermintaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubMenuPermintaanActionPerformed
        if (panelUtama != null) {
            panelUtama.showForm("cardDaftarPermintaan");
        }
    }//GEN-LAST:event_btnSubMenuPermintaanActionPerformed

    private void btnTambahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahBarangActionPerformed
        if (panelUtama != null) {
            panelUtama.showForm("cardTambahBarang");
        }
    }//GEN-LAST:event_btnTambahBarangActionPerformed

    private void btnSubMenuEditStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubMenuEditStokActionPerformed
        if (panelUtama != null) {
            panelUtama.showForm("cardEditStok");
        }
    }//GEN-LAST:event_btnSubMenuEditStokActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuBarang;
    private javax.swing.JButton btnMenuPermintaan;
    private javax.swing.JButton btnSubMenuEditStok;
    private javax.swing.JButton btnSubMenuPermintaan;
    private javax.swing.JButton btnSubMenuStok;
    private javax.swing.JButton btnTambahBarang;
    private javax.swing.JLabel icnInventrack;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNamaGudang;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlMenuContainer;
    private javax.swing.JPanel pnlProfile;
    private javax.swing.JPanel pnlSubMenuBarang;
    private javax.swing.JPanel pnlSubMenuPermintaan;
    // End of variables declaration//GEN-END:variables
}
