/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.anomaly.inventrack.ui.panels;

import com.anomaly.inventrack.models.Barang;
import com.anomaly.inventrack.services.MasterDataService;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class TambahBarangPanel extends javax.swing.JPanel {
    
    private final MasterDataService masterService;

    /**
     * Creates new form DashboardPanel
     */
    public TambahBarangPanel() {
        initComponents();
        masterService = new MasterDataService();
        
        setupInteractions();
        loadHelperData();
    }
    
    private void setupInteractions() {
        cmbKategoriHelper.addActionListener(e -> {
            String pilihan = (String) cmbKategoriHelper.getSelectedItem();
            if (pilihan != null && !pilihan.equals("- Pilih -")) {
                txtKategori.setText(pilihan);
            }
        });

        cmbSatuanHelper.addActionListener(e -> {
            String pilihan = (String) cmbSatuanHelper.getSelectedItem();
            if (pilihan != null && !pilihan.equals("- Pilih -")) {
                txtSatuan.setText(pilihan);
            }
        });
        
        btnSimpan.addActionListener(e -> prosesSimpanBarang());
    }
    
    public final void loadHelperData() {
        List<Barang> listBarang = masterService.getAllBarang();
        
        Set<String> kategoriUnik = new HashSet<>();
        Set<String> satuanUnik = new HashSet<>();
        
        for (Barang b : listBarang) {
            if (b.getKategori() != null) kategoriUnik.add(b.getKategori());
            if (b.getSatuan() != null) satuanUnik.add(b.getSatuan());
        }
        
        cmbKategoriHelper.removeAllItems();
        cmbKategoriHelper.addItem("- Pilih -");
        for (String k : kategoriUnik) cmbKategoriHelper.addItem(k);
        
        cmbSatuanHelper.removeAllItems();
        cmbSatuanHelper.addItem("- Pilih -");
        for (String s : satuanUnik) cmbSatuanHelper.addItem(s);
    }
    
    private void prosesSimpanBarang() {
        String idStr = txtIdBarang.getText().trim();
        String nama = txtNamaBarang.getText().trim();
        String kategori = txtKategori.getText().trim();
        String satuan = txtSatuan.getText().trim();
        String deskripsi = txtaDeskripsi.getText().trim();
        
        if (idStr.isEmpty() || nama.isEmpty() || kategori.isEmpty() || satuan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID, Nama, Kategori, dan Satuan wajib diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int idBarangManual = Integer.parseInt(idStr);

            Barang barangBaru = new Barang(idBarangManual, nama, kategori, satuan, deskripsi);

            masterService.createBarang(barangBaru);

            JOptionPane.showMessageDialog(this, "Berhasil menyimpan barang: " + nama);
            resetForm();
            loadHelperData();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID Barang harus berupa ANGKA!", "Format Salah", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Gagal", JOptionPane.ERROR_MESSAGE);
        }
    }
        
    
    private void resetForm() {
        txtIdBarang.setText("");
        txtNamaBarang.setText("");
        txtKategori.setText("");
        txtSatuan.setText("");
        txtaDeskripsi.setText("");
        cmbKategoriHelper.setSelectedIndex(0);
        cmbSatuanHelper.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlWrapper = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblIdBarang = new javax.swing.JLabel();
        txtIdBarang = new javax.swing.JTextField();
        lblNamaBarang = new javax.swing.JLabel();
        lblKategori = new javax.swing.JLabel();
        lblSatuan = new javax.swing.JLabel();
        lblDeskripsi = new javax.swing.JLabel();
        txtNamaBarang = new javax.swing.JTextField();
        txtKategori = new javax.swing.JTextField();
        txtSatuan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDeskripsi = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();
        cmbSatuanHelper = new javax.swing.JComboBox<>();
        cmbKategoriHelper = new javax.swing.JComboBox<>();

        setLayout(new java.awt.BorderLayout());

        pnlWrapper.setLayout(new java.awt.GridBagLayout());

        lblIdBarang.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblIdBarang.setText("ID Barang");

        txtIdBarang.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblNamaBarang.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNamaBarang.setText("Nama Barang");

        lblKategori.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblKategori.setText("Kategori");

        lblSatuan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSatuan.setText("Satuan");

        lblDeskripsi.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDeskripsi.setText("Deskripsi");

        txtNamaBarang.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtKategori.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtSatuan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtSatuan.addActionListener(this::txtSatuanActionPerformed);

        txtaDeskripsi.setColumns(20);
        txtaDeskripsi.setRows(5);
        jScrollPane1.setViewportView(txtaDeskripsi);

        btnSimpan.setText("Simpan");

        cmbSatuanHelper.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbSatuanHelper.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbKategoriHelper.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbKategoriHelper.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblIdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtIdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbKategoriHelper, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbSatuanHelper, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSimpan)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtIdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbKategoriHelper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbSatuanHelper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSimpan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlWrapper.add(jPanel2, new java.awt.GridBagConstraints());

        jScrollPane2.setViewportView(pnlWrapper);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSatuanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbKategoriHelper;
    private javax.swing.JComboBox<String> cmbSatuanHelper;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDeskripsi;
    private javax.swing.JLabel lblIdBarang;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblNamaBarang;
    private javax.swing.JLabel lblSatuan;
    private javax.swing.JPanel pnlWrapper;
    private javax.swing.JTextField txtIdBarang;
    private javax.swing.JTextField txtKategori;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtSatuan;
    private javax.swing.JTextArea txtaDeskripsi;
    // End of variables declaration//GEN-END:variables
}
